### ISSUE TITLE
Udp protocol

### ISSUE THREAD

**Issue by griffinmt** [igorantolic/esp32-alexa-wemo-emulator#10]
Can you explain how you determined how to communicate with Alexa. Is it documented somewhere? I want to do the same for Google Home.

**Comment by igorantolic** [comment]
Read the [README.md](https://github.com/igorantolic/esp32-alexa-wemo-emulator/blob/master/README.md)
You will find reference to repositories and people which did the hard work investigating how it might work.
The essence is to "behave like a device which works". This way you can trick Alexa and Google home to use these "less secure" protocols to gain the goal. Otherwise all that devices will ask for more complex integration.

The alternative is using home automation like Home Assistant and then to use esphome. Additionally with paid nabulacasa you have more control over all that devices but also more useful use cases.  And use cases which are much more complex.
